// Generated by CoffeeScript 1.3.1
(function() {
  var addresses, stickySessions, targetServer;

  addresses = [];

  stickySessions = [];

  targetServer = null;

  exports.stickyStrategy = function(req, res, next) {
    if ((req.headers.cookie != null) && (stickySessions[req.headers.cookie] != null)) {
      targetServer = stickySessions[req.headers.cookie];
    }
    return next();
  };

}).call(this);
