// Generated by CoffeeScript 1.3.1
(function() {
  var _this = this;

  this.store = require('./satellite/stores/default');

  exports.addAddress = function(address) {
    var index;
    index = _this.store.addresses.get().indexOf(address);
    if (index === -1) {
      return _this.store.addresses.add(address);
    }
  };

  exports.removeAddress = function(address) {
    var addr, cookie, _ref, _results;
    _this.store.addresses.remove(address);
    _ref = _this.store.stickySessions.get();
    _results = [];
    for (cookie in _ref) {
      addr = _ref[cookie];
      if (addr === address) {
        _results.push(_this.store.stickySessions["delete"](cookie));
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  exports.roundRobinStrategy = require('./satellite/strategies/roundRobin').strategy;

  exports.stickySessionStrategy = require('./satellite/strategies/stickySessions').strategy;

}).call(this);
