// Generated by CoffeeScript 1.3.1
(function() {
  var _this = this;

  this.addresses = [];

  this.targetAddress = null;

  this.roundRobin = require('./satellite/strategies/roundRobin');

  this.stickySessions = require('./satellite/strategies/stickySessions');

  exports.addAddress = function(address) {
    var index;
    index = _this.addresses.indexOf(address);
    if (index === -1) {
      return _this.addresses.push(address);
    }
  };

  exports.removeAddress = function(address) {
    var addr, cookie, index, _ref, _results;
    index = _this.addresses.indexOf(address);
    _this.addresses.splice(index, 1);
    _ref = _this.stickySessions;
    _results = [];
    for (cookie in _ref) {
      addr = _ref[cookie];
      if (addr === address) {
        _results.push(delete _this.stickySessions[cookie]);
      } else {
        _results.push(void 0);
      }
    }
    return _results;
  };

  exports.stickySessionStrategy = this.stickySessions.strategy;

  exports.roundRobinStrategy = this.roundRobin.strategy;

}).call(this);
