// Generated by CoffeeScript 1.3.1
(function() {
  var satellite;

  satellite = require('../../satellite');

  exports.strategy = function(req, res, next) {
    return satellite.store.addresses.get(function(addresses) {
      return satellite.store.targetAddressIndex.get(function(number) {
        var newAddress;
        newAddress = addresses[number];
        return satellite.store.targetAddress.set(newAddress, function(res) {
          if (number === addresses.length - 1) {
            return satellite.store.targetAddressIndex.reset(function(res) {
              return next();
            });
          } else {
            return satellite.store.targetAddressIndex.increment(function(res) {
              return next();
            });
          }
        });
      });
    });
  };

}).call(this);
