// Generated by CoffeeScript 1.3.1
(function() {
  var satellite;

  satellite = require('../../satellite');

  exports.strategy = function(req, res, next) {
    satellite.store.targetAddress(satellite.store.addresses.get()[satellite.store.targetAddressIndex.get()]);
    if (satellite.store.targetAddressIndex.get() === satellite.store.addresses.get().length - 1) {
      satellite.store.targetAddressIndex.reset();
    } else {
      satellite.store.targetAddressIndex.increment();
    }
    return next();
  };

}).call(this);
