// Generated by CoffeeScript 1.3.1
(function() {
  var satellite,
    _this = this;

  satellite = require('../../satellite.coffee');

  this.targetAddressIndex = 0;

  this.strategy = function(req, res, next) {
    satellite.targetAddress = satellite.addresses[_this.targetAddressIndex];
    if (_this.targetAddressIndex === satellite.addresses.length - 1) {
      _this.targetAddressIndex = 0;
    } else {
      _this.targetAddressIndex += 1;
    }
    return next();
  };

}).call(this);
