// Generated by CoffeeScript 1.3.1
(function() {
  var satellite, setRandomTargetAddress,
    _this = this;

  satellite = require('../../satellite.coffee');

  this.sessions = {};

  setRandomTargetAddress = function() {
    var randomIndex;
    randomIndex = Math.floor(Math.random() * satellite.addresses.length);
    return satellite.targetAddress = satellite.addresses[randomIndex];
  };

  this.strategy = function(req, res, next) {
    if (req.headers.cookie != null) {
      if (_this.sessions[req.headers.cookie] != null) {
        satellite.targetAddress = _this.sessions[req.headers.cookie];
      } else {
        _this.sessions[req.headers.cookie] = setRandomTargetAddress();
      }
    } else {
      setRandomTargetAddress();
    }
    return next();
  };

}).call(this);
