// Generated by CoffeeScript 1.3.1
(function() {
  var satellite, setRandomTargetAddress,
    _this = this;

  satellite = require('../../satellite');

  setRandomTargetAddress = function(cb) {
    if (cb == null) {
      cb = null;
    }
    return satellite.store.addresses.get(function(addresses) {
      var randomIndex;
      randomIndex = Math.floor(Math.random() * addresses.length);
      return satellite.store.targetAddress.set(addresses[randomIndex], function(res) {
        if (cb != null) {
          return cb();
        }
      });
    });
  };

  exports.strategy = function(req, res, next) {
    if (req.headers.cookie != null) {
      return satellite.store.stickySessions.get(req.headers.cookie, function(result) {
        if (result != null) {
          return satellite.store.targetAddress.set(result, function(res) {
            return next();
          });
        } else {
          return setRandomTargetAddress(function() {
            return satellite.store.targetAddress.get(function(address) {
              return satellite.store.stickySessions.set(req.headers.cookie, address, function(status) {
                return next();
              });
            });
          });
        }
      });
    } else {
      return setRandomTargetAddress(function() {
        return next();
      });
    }
  };

}).call(this);
