// Generated by CoffeeScript 1.3.1
(function() {
  var satellite, setRandomTargetAddress,
    _this = this;

  satellite = require('../../satellite');

  setRandomTargetAddress = function() {
    var randomIndex;
    randomIndex = Math.floor(Math.random() * satellite.store.addresses.get().length);
    return satellite.store.targetAddress(satellite.store.addresses.get()[randomIndex]);
  };

  exports.strategy = function(req, res, next) {
    if (req.headers.cookie != null) {
      if (satellite.store.stickySessions.get(req.headers.cookie) != null) {
        satellite.store.targetAddress(satellite.store.stickySessions.get(req.headers.cookie));
      } else {
        satellite.store.stickySessions.set(req.headers.cookie, setRandomTargetAddress());
      }
    } else {
      setRandomTargetAddress();
    }
    return next();
  };

}).call(this);
